# Example: Nix-based CI that matches local development
# Use this when you develop locally with `nix develop`
#
# Place in: .github/workflows/ci.yml

name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # Option 1: Use composite actions directly
  test:
    name: Test (Nix)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: reed/ci/actions/nix-setup@main
        with:
          nix-installer: determinate  # or 'official'
          # Optional: Enable Cachix for faster builds
          # enable-cachix: true
          # cachix-name: your-cache
          # cachix-auth-token: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - uses: reed/ci/actions/nix-elixir-test@main
        with:
          coverage: false

  quality:
    name: Quality (Nix)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: reed/ci/actions/nix-setup@main
        with:
          nix-installer: determinate

      - uses: reed/ci/actions/nix-elixir-quality@main
        with:
          credo-strict: true
          dialyzer: false  # Enable if you use Dialyzer

  coverage:
    name: Coverage (Nix)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: reed/ci/actions/nix-setup@main
        with:
          nix-installer: determinate

      - uses: reed/ci/actions/nix-elixir-test@main
        with:
          coverage: true
          coverage-tool: coveralls.github

  # Option 2: Use reusable workflow (when published)
  # ci:
  #   uses: reed/ci/.github/workflows/nix-elixir-ci.yml@main
  #   with:
  #     nix-installer: determinate
  #     run-coverage: true
  #     run-dialyzer: false
  #   secrets:
  #     CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
